# Generated by Django 6.0.2 on 2026-03-30 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livevc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='handraiserequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voicepanel',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_panels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmember',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='livevc.voicepanel'),
        ),
        migrations.AddField(
            model_name='handraiserequest',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_raises', to='livevc.voicepanel'),
        ),
        migrations.AlterUniqueTogether(
            name='panelmember',
            unique_together={('panel', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='handraiserequest',
            unique_together={('panel', 'user')},
        ),
    ]
