# Generated by Django 6.0.2 on 2026-02-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livevc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('learner', 'Learner')], default='learner', max_length=20),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
