# Generated by Django 6.0.2 on 2026-02-27 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livevc', '0002_alter_userprofile_google_id_alter_userprofile_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicePanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(choices=[('ai_tech', 'AI & Technology'), ('innovation', 'Innovation'), ('spiritual', 'Spiritual & Philosophy'), ('skills', 'Skills & Learning'), ('general', 'General Discussion')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_members', models.IntegerField(default=4)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_panels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PanelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-Host'), ('speaker', 'Speaker'), ('listener', 'Listener')], default='listener', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_hand_raised', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='livevc.voicepanel')),
            ],
            options={
                'unique_together': {('panel', 'user')},
            },
        ),
        migrations.CreateModel(
            name='HandRaiseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('is_addressed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_raises', to='livevc.voicepanel')),
            ],
            options={
                'unique_together': {('panel', 'user')},
            },
        ),
    ]
