# Generated by Django 6.0.2 on 2026-02-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livevc', '0003_voicepanel_panelmember_handraiserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicepanel',
            name='peer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
