"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/   

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/   
"""

from pathlib import Path
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me-in-production')

DEBUG = True

ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',
    'users',
    'ml_apps',
    'livevc',
    'voice_rooms',
    'lms',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'lms.access_control.CourseAccessMiddleware',  # Course content protection
]

ROOT_URLCONF = 'backend.urls'

# CORS SETTINGS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'x-requested-with',
    'accept',
    'origin',
    'x-csrftoken',
    'x-api-key',
    'cache-control',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

ALLOWED_HOSTS = [
    'app.seekhowithrua.com',
    'seekhowithrua.com',
    'www.seekhowithrua.com',
    'api.seekhowithrua.com',
    'django-react-ml-app.onrender.com',
    'localhost',
    '127.0.0.1',
    '*',
]

# Explicit CORS origins for security (works with ALLOW_ALL_ORIGINS as backup)
CORS_ALLOWED_ORIGINS = [
    'https://app.seekhowithrua.com',
    'https://seekhowithrua.com',
    'https://www.seekhowithrua.com',
    'https://lms.seekhowithrua.com',
    'https://gaming.seekhowithrua.com',
    'https://animation.seekhowithrua.com',
    'https://services.seekhowithrua.com',
    'http://localhost:5173',
    'http://localhost:3000',
    'http://127.0.0.1:5173',
    'https://django-react-ml-app.vercel.app',
]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # Rate limiting — prevents brute force attacks
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',
        'user': '200/min',
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database — Supabase Transaction Pooler (environment variables)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', '6543'),
        'OPTIONS': {'sslmode': 'require'},
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ── SECURITY SETTINGS ─────────────────────────────────────────────────────────
# Render handles SSL at proxy level — NEVER set SECURE_SSL_REDIRECT = True
SECURE_SSL_REDIRECT            = False
SECURE_PROXY_SSL_HEADER        = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie security — tied to DEBUG so they work on Render free tier
# When DEBUG=True  → False (works on Render)
# When DEBUG=False → True  (production security)
SESSION_COOKIE_SECURE          = not DEBUG
CSRF_COOKIE_SECURE             = not DEBUG
SESSION_COOKIE_HTTPONLY        = True
CSRF_COOKIE_HTTPONLY           = True
SESSION_COOKIE_SAMESITE        = 'Lax'
CSRF_COOKIE_SAMESITE           = 'Lax'

# HSTS — tells browsers to always use HTTPS for 1 year
SECURE_HSTS_SECONDS            = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD            = True

# Browser security headers
SECURE_BROWSER_XSS_FILTER      = True
SECURE_CONTENT_TYPE_NOSNIFF    = True
X_FRAME_OPTIONS                = 'DENY'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Email Settings for LMS Notifications
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'SeekhoWithRua <noreply@seekhowithrua.com>')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', 'noreply@seekhowithrua.com')

# Email deliverability settings to avoid spam
EMAIL_SUBJECT_PREFIX = '[SeekhoWithRua] '
EMAIL_USE_LOCALTIME = True

# LMS Payment Settings - KEEP SECRET
LMS_UPI_ID = os.environ.get('LMS_UPI_ID', '')
LMS_MONTHLY_FEE = 1000  # Base fee in INR
LMS_REFERRAL_CONCESSION = 200  # ₹200 per referral

# Media files (for payment screenshots)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    'payment-reminder-7th': {
        'task': 'lms.tasks.send_payment_reminders',
        'schedule': 'crontab(day_of_month="7-10", hour="9", minute="0")',
    },
    'class-reminder-24h': {
        'task': 'lms.tasks.send_class_reminders',
        'schedule': 'crontab(hour="*/1", minute="0")',
    },
    'absence-checker': {
        'task': 'lms.tasks.check_continuous_absence',
        'schedule': 'crontab(hour="18", minute="0")',
    },
    'feedback-form-sender': {
        'task': 'lms.tasks.send_feedback_form_requests',
        'schedule': 'crontab(hour="20", minute="0")',
    },
}