# Generated by Django 6.0.2 on 2026-02-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='user_emp',
        ),
    ]
