# Generated by Django 6.0.2 on 2026-02-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
    ]
