# Generated by Django 6.0.2 on 2026-02-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True},
        ),
    ]
